{% set version = "1.3.1" %}

package:
  name: pdfminer3k
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pdfminer3k/pdfminer3k-{{ version }}.tar.gz
  sha256: 1670de8ddb9aaff8f28d61abc918e6a85c469fd876a00d7a0fddf735088ef6ce

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - pytest >=2.0
    - ply >=3.4

test:
  imports:
    - pdfminer

about:
  home: https://github.com/jaepil/pdfminer3k
  license: MIT
  license_family: MIT
  summary: 'pdfminer3k is a Python 3 port of pdfminer — a tool for extracting
  information from PDF documents'

  description: |
    pdfminer3k is a Python 3 port of pdfminer.
    PDFMiner is a tool for extracting information from PDF documents.
    Unlike other PDF-related tools, it focuses entirely on getting
    and analyzing text data. PDFMiner allows to obtain
    the exact location of texts in a page, as well as
    other information such as fonts or lines.
    It includes a PDF converter that can transform PDF files
    into other text formats (such as HTML). It has an extensible
    PDF parser that can be used for other purposes instead of text analysis.
  doc_url: https://github.com/jaepil/pdfminer3k
  dev_url: https://github.com/jaepil/pdfminer3k

extra:
  recipe-maintainers:
    - nikicc
