appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: QXAPaqwU1CZIR82Gajg7QCKZo2Z5R0RbI84xlu6Or+rikM/Zms2K/xg+DIM8QCydCc4zvCIJ3ApBhik5jZGaypVsczZ+e5LSPEESa9zpOmSY0hiJteUINJzrtHLF2rGhRUbXchZO1l6bmOeTkVMqJuhUFLa9B811hK/dnBMZEtjsBLJCVXMFQC1eDAU9ByQq02Wy6ekVOAXoZVHfwzR1EN4bfhrtiwYBqGVdd68sII7EgjQYRC0fFeNA/W+FEDXOzTjiURjaC3UounkLUVNu12iA3tHIOzs9qs/Hc0tG5DPXL8x9emCxsqb7yaGJLY75woEvIGtAsaa7ZXY2FqB/anFF6oC219Qfl4bffXv5YzV2YjPZJbU5BMJP+2EcSeGXvbYSDIMojROlIGA0U9dcaOvJKjqSKA4jKLG/xovEA2zeud9eRqvoX460P76GcuSY+N1S4GWth6dWPX8VWT8qX7WjVJyiXHw60t1o5aQcwqruZN3xWTRvPtcFkEzoQMqZkHGTr9TbId92YO8x9uQBcA8XEwFEQtFfCKNK2wIicfy/o77D/mHra6W8PtdlGF2EM50CZjrDY4D1JIzjCPoH1OKlcm2gcrcI6C4D2GMkPN4O4r5ICT87SWAzSb4OXQUArht4T2wAphEM9/QpIaNIyAsRocYl6JnTsEZxvJQV/CE=}
conda_forge_output_validation: true
