travis:
  secure:
    BINSTAR_TOKEN: jPhGYBt2gq47YzThmta3NWNMko3eu4Dr2zdr1oVWTNDbAOOGqAG++4mLsL3/of0NcYJs5ChiAVdyK0W7mkP23QUaetjrdWKrhk5FwmsAcbkjXelYJplvmVfrjHOIQf5Z6byy4ssJx51O+C7tP70MKSKAnKab7VAPfQDhrFAleR93nugIdMaNjQDg+9sBfvXq4SLWXiwnyZUJ1BvtFwjLk9FeyV/WqIP1wvjqnbenqgbsfbmSmZO4scWJ8nayhOwSo/gqxw3/VL7zh/OBYVLIfzotjCcODS7dzWZxPaJmmJZGoTuQRQZK+vWydnUeLb7en3Bw2PaO+kmKaCzKnMPe1C6Etjjo7zznd8sdmvRRmmEALq+k7EjIUIP5HXFqq80Px2SVPiR30axblJhaoPt9cnJrIw8jS3fkYkcrsvprSpw/8PZxiyTUkHVGzhn40617RTVhkAOJvAIMOhNWMDP44wfXZL/o+mqKx9S+S2o1chXpuJ99mFIYpRV6wKBlnoeoKXHW7LgI3kipmGb3KcdWGB3Z8UA21JQG5K8mTTHwyYbzoYIy/UP9WNzBoFXEvbbhGG5kTM68Q2cunSaWQJpMifNatuxOZkJbLVg6HydKgHVOCWs76bMMH0BEwD8JrLYeOR363Rr/CYgU2BdfL2QU0qQ2j0N6FSsZ7M+hKZfPl28=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
