travis:
  secure:
    BINSTAR_TOKEN: IKAIJTC+/n7I8R1ABfoND24L0vKI3liz4AWk7JA6ZJUaqlXleth73mXo1gC/M/funglpUwOwPUyTCfSbtmGHrQWsEoWNZaDCMKCMroU3/71diXi0djCgZmJr0QJrAeLCXr4iez9B6RS4bKGeatHz0XagniLVVOuD3McxX2L2CBkruz71w/F2tpXWYKQGsamv626WZOzo6flpnmQWHliVj5BeYqjAZqRb+EXxpHr5Jtv7jLwdcxwOYsDQdlMq67jX18HEkq5m6hyH3pjF8+EgSywquPQ78FeO4oZxjVtizzGgQpWeRDfHe/ZcTYxud+0ftf0E7tSeRLNhHQxdQOpKG6/YoamyISgua6HZZN1oEGt9/2G6KCoEGB7xdG8L4ahBGdT0FJrP1tM2ocWGde8qKmfwUA1sOcsIrxTWDIyMmMpePa0TjxUrbH/k+/v6P3Ptgy9kM6r2AZFVTdF38PnyMXfyXUYLyqbyyCYwg1SUm5JY59Pu8UwKUTYpE9+UVqCNSPun9z/qcpJhDqJ6yPp2qypNN0RUHdxqGwVUqfx1Ebz6DV+3mujobXEUaVND4KyBZ3BCIiwYzc9AO4J5DhTD+GJhgz7sCkzqpUa8nERksYFxXnJiaW0F3YeqEc+Yzr9tOcLuM0FMODUPfIwSENEmpe+Fij1PA/cL9m5DayGRQDg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
